# Generated by Django 5.0.6 on 2024-05-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('investment_duration', models.CharField(choices=[('1y', '1 year'), ('2y', '2 years'), ('4y', '4 years'), ('5y', '5 years'), ('6y', '6 years'), ('7y', '7 years'), ('8y', '8 years'), ('9y', '9 years'), ('10y', '10 years')], max_length=10)),
            ],
        ),
    ]
